ministryofjustice/hmpps-locations-inside-prison-api

- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/ResidentialAttribute.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationConstants.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationConstantsIntTest.kt
add apis to access locations within prisons
> MAP-636 add apis to get prison internal locations

- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/dto/LocationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/Location.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/NonResidentialLocation.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/ResidentialLocation.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationConstants.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/service/EventPublishAndAuditService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/service/LocationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationResourceIntTest.kt
Update LocationService and related classes for event handling and location attributes
Refactored LocationService, EventPublishAndAuditService, and various location classes in the project. Changes ensure proper event handling, improve attribute mapping in locations, and accommodate for hierarchy changes. Methods toDto() were extended to include parent information. ResidentialLocation, NonResidentialLocation patch update now over-writes attributes and usage
> MAP-792 Update LocationService and related classes for event handling and location attributes

- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/dto/LocationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/service/EventPublishAndAuditService.kt
The commit modifies the sequence of event publishing and traversal function calls in EventPublishAndAuditService to ensure proper event handling. It also improves the traverse function in LocationDto by adding a location to the locations list immediately upon traversal, enhancing the efficiency and accuracy of location management within the application.
> MAP-862 Improve event handling and traversal in Location services

- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/dto/LocationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/Location.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/repository/LocationHistoryRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/service/LocationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/service/NaturalOrderComparator.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationResourceIntTest.kt
- Return level of locations
- Return the heirarchy of a location
- Return a history of changes (last 10) for the current location
> MAP-1172 UI improvements

- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/dto/LocationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/Location.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/repository/CellLocationRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/service/LocationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationResourceIntTest.kt
This update allows the retrieval of inactive cells within specific layouts such as a wing or a landing within the prison.
> MAP-1163 Add functionality to retrieve inactive cells

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/Location.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/helper/UuidV7Generator.kt
A new custom UUID generator, UuidV7Generator, has been added to the project. The change replaces the previous random UUID generation strategy in the Location entity with this custom time-based UUID v7 generation. A new dependency for the java-uuid-generator library has been added to the project build configuration.
> MAP-1200 ✨ Added custom UUID generation for Location entity

- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/SpecialistCellType.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationConstantsIntTest.kt
Case and separation unit cell > Care and separation cell
Constant Supervision Cell > Constant supervision cell
> MAP-1496 Correct inconsistencies in cell type descriptions

- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/integration/CommonDataTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/integration/wiremock/PrisonerSearchMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/PrisonerLocationResourceTest.kt
As Integration Tests are not cover for this GET /prisoner-locations/prisonId/{prisonid} & /prisoner-locations/key/{key}, i have created this SECURITY and HappyPath tests.
> MAP-1457 42 PrisonerLocationResource map prisoner by prisonId

- build.gradle.kts
- gradle.properties
to fix CVE see [MAP-1571](https://dsdmoj.atlassian.net/jira/software/c/projects/MAP/boards/1354?selectedIssue=MAP-1571)
[MAP-1571]: https://dsdmoj.atlassian.net/browse/MAP-1571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MAP-1071 update dependencies

- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/LocationTest.kt
As LocationGroupDto children list have not been covered, added these lines
> MAP-1457 112 LocationGroupDto repo children test coverage KOVER red line

- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/PrisonSignedOperationCapacityUpdateIntTest.kt
Please keep this Tiny PR to cover 1 test scenario.
When PrisonID is 3 character but ID is not valid
PrisoniD Not Found Exception
> MAP-1457  22 PrisoniD Not Found

- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/dto/LocationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/Cell.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/Location.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/NonResidentialLocation.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/ResidentialLocation.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/service/LocationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationResidentialResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/service/SignedOperationCapacityServiceTest.kt
Returns the number of cell and room locations below the current location 
for GET `/locations/residential-summary/{prisonId}` new field added in the `parentLocation` and `prisonSummary`
```json
"numberOfCellLocations": 4
```
> MAP-1608 return a summary of total cell/rooms below the current location in residential-summary

- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/SyncAndMigrateResourceIntTest.kt
This Pull Request is the final stage of a previous Pull Request in order to cover all scenarios
https://github.com/ministryofjustice/hmpps-locations-inside-prison-api/pull/255 (I have simplified enum for a listOf but i had to create a clean merge)
and previosly 
https://github.com/ministryofjustice/hmpps-locations-inside-prison-api/pull/247
before
after
> MAP-1457 NomisMigrationRequest DeactivatedReason OTHER cover

- build.gradle.kts
As part of the Alert duties , I have update dependency where have been possible.
> Alert duties dependency update 

- build.gradle.kts
Scanning gave 2 vulnerabilities medium 
This should fix them
> MAP-1840  Force version of netty common to fix security issue + update sqs boot starter to 5.1.1

- build.gradle.kts
This is the upstream fix done for NETTY version.
> MAP-1840  This is the upstream fix done for NETTY version.

- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/LocationHistory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationResidentialResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/SyncAndMigrateResourceIntTest.kt
> MAP-1952: Update CONVERTED_CELL_TYPE label from `Converted cell type` to `Non-residential room`.

- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/dto/CellInitialisationRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/dto/CreateEntireWingRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/dto/CreateWingAndStructureRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/dto/LocationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/LocationHistory.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/ResidentialLocation.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationResidentialResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/service/LocationService.kt
- src/main/resources/db/migration/V1_52__add_resi_structure.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/integration/CommonDataTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationResidentialResourceTest.kt
This Pull Request introduces updates to location initialization, wing creation capabilities, and data modeling for residential locations inside a prison system. It adds enhancements for creating and managing structural hierarchies of locations such as Wings, Landings, and Cells, along with corresponding tests and database changes.
- Enhanced Wing Creation Logic:
- The CreateWingRequest class is replaced with CreateEntireWingRequest and CreateWingAndStructureRequest to handle different structures (e.g., Wings, Landings, Spurs, and Cells).
- New APIs added for creating both specific structures (/locations/create-wing) and entire hierarchical wings (/locations/create-entire-wing).
- Data Modeling Enhancements:
- Added wingStructure to define nested levels such as WING > LANDING > CELL.
- …
> MAP-2378 Add functionality to create structured residential locations

- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/dto/LocationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/Cell.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/CertificationApprovalRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/PendingLocationChange.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/ResidentialLocation.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/BulkUpdateResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/service/LocationService.kt
- src/main/resources/db/migration/V1_61__pending_approve_request.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/CellCertificateResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/CertificationResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationResidentialResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationResourceIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationTransformResourceTest.kt
- src/test/resources/repository/insert-dummy-locations.sql
This Pull Request introduces enhancements and refactorings related to prison location management, specifically catered around Certified Normal Accommodation (CNA), pending approval processes, and capacities. Key validations and functionalities improve data integrity, approval flow, and back-end structure associated with certification and resource updates. Test cases have been updated accordingly.
- Validation Enhancements:
- Added limits for certifiedNormalAccommodation to ensure values are between 0 and 99.
- Introduced new validations for cellMark (max 12 characters) and inCellSanitation flags for location cells.
- Approval Process Updates:
- Refactored the logic for handling pending approval changes in certification workflows.
- Introduced linking of pending location changes with …
> MAP-2473 Introduce support for pending change approvals with certified and sanitation updates

- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/dto/CreateEntireWingRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/dto/LocationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/Cell.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/PendingLocationChange.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/ResidentialLocation.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/service/LocationService.kt
- src/main/resources/db/migration/V1_63__store_only_max_cap_on_pending.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/integration/CommonDataTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/ApprovalRequestResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/CellCertificateResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/CertificationResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/DraftLocationResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationResidentialResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationTransformResourceTest.kt
The Pull Request introduces changes to handle "pending changes" in location capacities within the prison management system. It replaces the old pendingCapacity model with pendingChanges and modifies the associated logic to store and manage maximum capacity, working capacity, and certified normal accommodation (CNA) distinctly. Tests are updated accordingly to fit the new structure.
- Replaced pendingCapacity with pendingChanges throughout the application logic and DTOs.
- Updated database schema to remove capacity-specific columns from PendingLocationChange and added a dedicated maxCapacity column.
- Refactored capacity handling methods to align with the new structure:
- Attributes like maxCapacity, workingCapacity, and CNA are now handled individually instead of in a bundled Capacity …
> MAP-2510 "Refactor capacity and pending changes handling in locations"

- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/PrisonConfigurationResource.kt
- src/main/resources/db/routines/R__01_location_procedures.sql
This PR introduces updates to enhance role-based access control in the PrisonConfigurationResource class and modifies a database routine for improved data handling and cleanup.
- Role Authorization Update: Changes the authorization annotation and description in the API endpoints of PrisonConfigurationResource to align with the correct role (ROLE_LOCATION_CONFIG_ADMIN).
- Database Routine Adjustments: Adds new cleanup steps and updates an insertion query within R__01_location_procedures.sql to include a new field (certification_approval_required) and ensure comprehensive deletion of related data for a prison.
> MAP-2512 Update certification approval and configuration handling

- docs/0004-location-db-design.md
- helm_deploy/values-train.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/dto/CellCertificateDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/dto/CertificationApprovalRequestDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/dto/CertificationApprovalRequestLocationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/dto/LocationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/ApiExceptionHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/BulkUpdateResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/ErrorResponse.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationConstants.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationOccupancyResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/service/CertificationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/service/LocationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/service/PrisonConfigurationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/repository/LocationBuilder.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/DprReportingIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationConstantsIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/PrisonRollResourceIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/service/PrisonLocationServiceTest.kt
- Added functionality to identify and signify that a specialist cell type affects capacity.
- Removed unused imports and annotations from multiple files.
- Updated `@Schema` annotations to `@param:Schema` for consistency in Kotlin data classes.
- Refined log messages in exception handlers for better clarity.
- Fixed a minor typo in Helm values configuration.
> MAP-2694 Indicates that a specialist cell type affects capacity
