- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/ApiExceptionHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/ErrorCode.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/service/LocationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationResourceIntTest.kt
Added the adjudication room as a NonResidentialLocation type and updated hierarchy. Created a new exception, LocationAlreadyExistsException, that's handled within ApiExceptionHandler to maintain server resilience when trying to create or update to a location that already exists. Updated tests to cover these changes.
> MAP-800 Add exception handling for duplicate locations

- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/dto/LocationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/dto/PatchLocationRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/dto/UpdateLocationRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/dto/UpsertLocationRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/ResidentialLocation.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationResourceIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/SyncAndMigrateResourceIntTest.kt
This commit includes changes to refactor how attributes are represented in 'Location' objects across various files. The attributes are now represented as a 'Set' of 'ResidentialAttributeValue' objects rather than a 'Map'. This simplifies the structure of the 'Location' entities.
> MAP-801 Refactor attributes representation in Location objects

- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/Location.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/NonResidentialLocation.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/ResidentialLocation.kt
Orphan removal attribute has been added to three OneToMany relationships in the Location, NonResidentialLocation, and ResidentialLocation classes. This ensures that when a parent entity is removed, all its related children entities will be automatically deleted, improving data cleanup. Furthermore, the update method in Residential class now checks if attributes are not null before invoking the function to record history of attributes changes.
> MAP-614 Enable orphanRemoval for multiple OneToMany relationships

- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/NonResidentialLocation.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/NonResidentialUsage.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/ResidentialAttribute.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/ResidentialLocation.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationResourceIntTest.kt
The CascadeType for @ManyToOne has been removed in both ResidentialAttribute.kt and NonResidentialUsage.kt.
The orphanRemoval property is now set to true in ResidentialLocation.kt and NonResidentialLocation.kt.
Multiple tests related to location have been updated
> MAP-614 Update fetching strategy and edit tests

- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/dto/MigrateHistoryRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/Location.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/NonResidentialUsage.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/ResidentialAttribute.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/MigrationResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/service/SyncService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/SyncAndMigrateResourceIntTest.kt
Updated the SyncService to include a method for migrating location history. A new endpoint has been added to the MigrationResource that calls this method. The unnecessary CascadeType imports in ResidentialAttribute and NonResidentialUsage have been removed. Additionally, test coverage was expanded to include the new endpoint and service method.
> MAP-614 Add location history migration endpoint and functionality

- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/dto/CreateWingRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/dto/LocationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/dto/UpsertLocationRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/Cell.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/Location.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/NonResidentialLocation.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/ResidentialLocation.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/service/LocationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/repository/LocationBuilder.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/repository/LocationRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationResourceIntTest.kt
This commit introduces a feature for creating prison wings with defined landings and cells. This implementation also includes unit tests for the functions added, ensuring the correct status responses are returned. As part of this new feature, the request body validation has been included to prevent incorrect requests or the creation of duplicate locations. Additionally, a minor typo fix in a variable name from `reactivationDate` to `proposedReactivationDate` was implemented.
> MAP-848 Add functionality to create prison wings

- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/service/EventPublishAndAuditService.kt
The commit changes the hardcoded event type 'LOCATION_AMENDED' to use the method parameter 'eventType' in the publishEvent calls for sublocations. This ensures the correct event type is sent for each sublocation.
> MAP-862 Fix event type in EventPublishAndAuditService

- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/dto/UpsertLocationRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/service/SyncService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/SyncAndMigrateResourceIntTest.kt
Enhanced the UpsertLocationRequest class to include a parentId attribute that represents the UUID of the parent location, if it exists. Also updated the related SyncAndMigrateResourceIntTest.kt and SyncService.kt to handle this parameter. This provides an alternative method to associate a location with its parent, offering flexibility in location management processes.
> MAP-876 Add parentId to UpsertLocationRequest

- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/repository/LocationRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/service/LocationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationResourceIntTest.kt
ticket:
_POST prisonLocationsByKeys(keys[]): Location[], to get the location descriptions for a list of keys provided in one call, for when we show lists of video bookings. Useful if this could avoid being specific to one prison because there could be a use-case where one video booking could have 2 or more prisoners, in different prisons, as co-defendants._ 
btw, should locationResourceIntTest.kt Line 160 say landing1 as the inactive cell is on landing 1 not landing 3?
> MAP-1095 new endpoint to get active locations by their path hierarchy

- src/main/resources/db/migration/V1_29__data_fix_wheelchair.sql
This PR updates specialist_cell records in the database where the specialist_cell_type is 'WHEELCHAIR_ACCESSIBLE', setting them to 'ACCESSIBLE_CELL'. It also removes any lingering records with the 'WHEELCHAIR_ACCESSIBLE' type to ensure data consistency.
> MAP-1202 🐛 Update wheelchair accessible cells in DB

- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/Location.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationResourceIntTest.kt
refactored so that dto has same data and structure as the corresponding dto in whereaboutsApi
The two should match but currently in the case of the location api, the dto didn't sort children and the key value for the group didn't match
> MAP-1030 changed dto to use code and do sort

- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/Location.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/LocationTest.kt
This is to display an alternative when 'localName'  has not been set for a wing/landing/spur
> MAP-1030 provide alternative value for dto.name

- src/main/resources/application.yml
In the application configuration, the maximum pool size for the database connection has been increased from 10 to 20. Additionally, a new max lifetime setting has been introduced at a value of 600000ms, aiming to improve the application's management of database connections.
> MAP-1284 Increase database pool size and add max lifetime

- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/dto/LocationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/dto/NomisMigrationRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/Cell.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/ResidentialLocation.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/repository/LocationRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/service/SyncService.kt
- src/main/resources/db/migration/V1_32_data_fix_missing_accommodation_types.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/config/LocalStackContainer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/SyncAndMigrateResourceIntTest.kt
Added an accommodation type mapping function in the ResidentialLocation.kt file and revised SQL scripts to update and insert accommodation types based on conditions in the V1_32_data_fix_missing_accommodation_types.sql file. Modified methods in NomisMigrationRequest.kt, Cell.kt, and LocationDto.kt to add 'STANDARD_ACCOMMODATION' for 'NORMAL_ACCOMMODATION' types and adjust the flow, allowing for more accurate data representation.
> MAP-1288 Add accommodation type mapping and conditionals in migrations

- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/dto/LegacyLocation.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/Location.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/ErrorResponse.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/SyncAndMigrateResourceIntTest.kt
The code now properly handles locations that have been permanently deactivated. A new boolean field, "permanentlyDeactivated", has been added to the LegacyLocation class. Additionally, sync tests have been updated to include cases where the location has been permanently deactivated and can't be updated in NOMIS. Non-NULL JSON object is now included for error responses.
> MAP-1291 Add support for permanently deactivated locations in NOMIS legacy view

- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/Cell.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/ResidentialLocation.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationResourceIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/SyncAndMigrateResourceIntTest.kt
The method for calculating cell capacity in ResidentialLocation.kt has been updated to exclude the cell itself from the calculation. Additionally, 'capacity' and 'certification' fields have been omitted from the conversion to DTO in Cell.kt. Changes have also been reflected in the corresponding test files, modifying the expected working capacity to zero in these tests.
> MAP-1354 Remove-working-cap-value-from-inactive-cells

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/config/ActivePrisonConfig.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/config/ActivePrisonsInfo.kt
- src/main/resources/application-dev.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/integration/health/InfoTest.kt
- src/test/resources/application-test.yml
Introduced a new config value, SERVICE_ACTIVE_PRISONS, to manage the list of active prisons. This info is now available through the /info endpoint, and is configurable via environment variables. Added corresponding tests to verify this change.
> MAP-1365 Add active prisons info to service config

- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/repository/ResidentialLocationRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationOccupancyResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/service/LocationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/service/PrisonerSearchService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/integration/wiremock/PrisonerSearchMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationCapacityResourceIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationResourceIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/service/PrisonLocationServiceTest.kt
This replaces the prison API and whereabouts API endpoints that find capacity of cells within prison.
It makes use of prisoner search to look up locations and check if prisoners are in the cells.  Capacity is then used to work out if space is available based on existing logic.
> MAP-1371 Provide cells with capacity endpoint 

- .env
- README.md
- build.gradle.kts
Introduce a test coverage plugin to allow developers to track their testing
Documentation:
https://kotlin.github.io/kotlinx-kover/gradle-plugin/
Example command to generate a HTML report locally:
`./gradlew koverHtmlReport`
Example report output:
Later on we can look at ways of generating these automatically with CircleCI and adopt it in our other projects using Kotlin.
> [MAP-1359] Add Kover plugin to generate code coverage reports

- .gitignore
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/dto/PatchLocationRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/Cell.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/service/LocationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationResourceIntTest.kt
Initial version, still need to add to the validation logic, see [issue](https://dsdmoj.atlassian.net/browse/MAP-1395?focusedCommentId=480549)
Adds a new endpoint and removes the update of the specialist cell types as part of **PATCH  /locations/residential/{id}**
> MAP-1395 Separate endpoint for updating specialist cell types to allow removal of all types

- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/service/PrisonLocationServiceTest.kt
MAP-1457 41 PrisonerSearchService DataClass Alert covered
PrisonerSearchService 66%
I have added test coverage to this Data Class 
data class Alert(
@Schema(description = "Alert type", example = "X", required = true)
val alertType: String,
@Schema(description = "Alert code", example = "XA", required = true)
val alertCode: String,
@Schema(description = "Active alert", example = "true", required = true)
val active: Boolean,
@Schema(description = "Expired", example = "false", required = true)
val expired: Boolean,
)
> MAP-1457 41 PrisonerSearchService DataClass Alert covered

- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationIntTest.kt
As Integration Tests is not cover /locations/id when id is not found . this is a validation test for that scenario.
> MAP1457  Resource Location id not found validation test

- gradle.properties
Removal was done in previous commit and is possibly the cause of a build fail in Circle
> MAP-1571 revert the removal of gradle property

- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/Cell.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationResidentialResourceTest.kt
for non resi
Fortunately, there is an existing test which does the change from OTHER to another type, I just added a check that the value was reset to null and implemented the logic.
The issue is described in https://dsdmoj.atlassian.net/browse/MAP-1669
> Reset the value for OTHER when changing to another type

- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationPrisonIdResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/service/LocationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/service/LocationServiceTest.kt
enabling sorting of response by localName and formatting by localName for 
- /locations/prison/${prisonId}/non-residential-usage-type/{usageType}`
- /locations/{id}
- /locations/prison/{prisonId}/location-type/{locationType}
options for sorting and formatting passed in query params  sortByLocalName and formatLocalName. Defaulted to false.
> MAP-1808 enable sorting and formatting for some endpoints

- src/main/resources/db/migration/V1_50__remove_old_status_columns.sql
This Pull Request removes unused status columns (active and archived) from the location table in the database schema.
Added a migration script (V1_50__remove_old_status_columns.sql) to:
- Drop the active column from the location table, if it exists.
- Drop the archived column from the location table, if it exists.
> MAP-2358 Remove old status columns from location table

- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/EventBaseResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/SignedOperationCapacityResource.kt
- src/main/resources/reports/residential-usage.json
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/integration/wiremock/ManageUsersApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/DprReportingIntegrationTest.kt
This Pull Request introduces enhancements and adjustments to the codebase, focusing on event handling, scope/access checks, and security-related functionality. It includes changes to event publishing methods, additional integration tests, improved test data mocking, and minor fixes in a JSON report configuration.
- DPR Report Fixes:
- Adjusted date formatting in the residential-usage.json file for consistency (uses 24-hour format).
- Removed an unused default value field from the configuration.
- Event Methods Updates:
- Refactoring of publishSignedOpCapChange to default event type SIGNED_OP_CAP_AMENDED.
- Changed access modifier for auditAndEmit from protected to private.
- Integration Test Improvements:
- Added new dynamic tests for endpoint authorization in IntegrationTestBase.
- …
> MAP-2405 Fix datetime in transaction report and add tests

- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/dto/CellInitialisationRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationResidentialResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/service/LocationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationResidentialResourceTest.kt
This pull request introduces enhancements to support the creation of cells on higher hierarchical levels. The changes include:
- Adding an optional `newLevelAboveCells` field in the `CellInitialisationRequest`.
- Updating service logic to handle requests with or without parent-level structures.
- Implementing validations to prevent location code clashes.
- Simplifying related DTOs and test implementations for better maintainability.
- Refactored CellInitialisationRequest:
- Removed redundant fields (newLevelCode, newLevelDescription, etc.).
- Added the newLevelAboveCells data class for handling structural locations more robustly.
- Enhanced validation rules to ensure either a parentLocation or newLevelAboveCells is mandatory.
- Removed the internal createLocation function and incorporated …
> MAP-2401 Creation of cells on new or existing level, create any level with or without cells, validate no location clashes

- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/dto/CellInitialisationRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/SpecialistCellType.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/service/LocationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationResidentialResourceTest.kt
- Refactored `createLandingRequest` to a Kotlin function for improved test readability and maintainability.
- Added validation for specialist cell types that affect capacity when CNA or working capacity are not zero.
- Updated schema and DTOs to support related field changes for better input handling.
This Pull Request introduces significant updates to the cell creation logic and related files. The changes primarily affect the handling of CellInitialisationRequest, inclusion of additional constraints and properties to cells, amendments to the SpecialistCellType behavior, as well as corresponding updates to services and tests.
- Updated CellInitialisationRequest DTO:
- Added a new field accommodationType with default value NORMAL_ACCOMMODATION.
- Refactored inCellSanitation to be specific …
> MAP-2412 Refactor cell creation logic and add specialist cell validations

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
This Pull Request updates configuration values across three Helm deployment files to correct the naming of an SQS queue secret.
- Renamed the key sqs-update-from-external-system-events-secret to sqs-update-from-external-system-events-queue-secret in the following files:
- values-dev.yaml
- values-preprod.yaml
- values-prod.yaml
The modification ensures consistent and accurate naming for the corresponding secret in the SQS queue configurations.
> Rename SQS secret key in Helm values files

- src/main/resources/application-localstack.yml
- src/main/resources/application-train.yml
- src/test/resources/application-test.yml
The Pull Request updates multiple configuration YAML files to replace hardcoded queue and DLQ names with dynamically generated UUIDs. These changes likely aim to enhance configurability and reduce hardcoding.
- In application-localstack.yml, replaced hardcoded queueName and dlqName values for updatefromexternalsystemevents with random UUIDs.
- In application-train.yml, added new configuration entries for updatefromexternalsystemevents with dynamically generated queueName and dlqName.
- In application-test.yml, updated queueName and dlqName values for updatefromexternalsystemevents to use random UUIDs instead of hardcoded names.
> MAP-2449 `Update queue and DLQ configurations to use random UUIDs`

- src/main/resources/application-train.yml
Corrected the indentation of `updatefromexternalsystemevents` queue and DLQ configuration in `application-train.yml`. This ensures proper YAML parsing and adherence to structure expectations
> MAP-2449 Fix indentation in train YAML queue configuration

- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/dto/LocationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/Cell.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/Location.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/NonResidentialLocation.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/ResidentialLocation.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/VirtualResidentialLocation.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/service/LocationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/DraftLocationResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationResidentialResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationTransformResourceTest.kt
- src/test/resources/repository/insert-dummy-locations.sql
This Pull Request introduces changes to support tracking "pending capacity" details for locations, such as draft or pending approval statuses.
- **Addition of pendingCapacity Field**: Added `pendingCapacity` to `LocationDto` to capture capacity details for draft or pending approval locations.
- **Refactoring**:
- Replaced and simplified capacity handling methods (e.g., `getDerivedMaxCapacity` was refactored to `calcMaxCapacity`).
- Removed unused `includePendingChange` parameter and its associated logic across DTO and service files.
- **Logic Update for isTemporarilyDeactivated**: Now considers draft status in its check.
- **Test Updates**:
- Adjusted tests to incorporate `pendingCapacity` changes.
- Added new test data to validate updated capacity logic.
- **SQL Updates**: Added a …
> MAP-2442 Add pending capacity handling for draft locations and update capacity calculations

- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/dto/CellCertificateDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/CellCertificate.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/Location.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/ResidentialLocation.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/service/CellCertificateService.kt
- src/main/resources/db/migration/V1_57__new_columns_on_cell_cert.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/CellCertificateResourceTest.kt
This Pull Request introduces changes to extend cell certification functionality in the system. It enhances the data model, modifies logic to include hierarchical location structures, adds new fields to accommodate converted cell types, and enriches test coverage.
- Enhanced DTO and JPA Models:
- Updated CellCertificateDto and CellCertificateLocationDto to add fields for localName, level, status, convertedCellType, and subLocations.
- Adjusted serialization/deserialization logic and filtering criteria.
- Modified CellCertificate and CellCertificateLocation JPA classes to  introduce new fields (convertedCellType, hierarchical sub-locations).
- Service and Helper Logic:
- Enhanced methods like toCellCertificateLocation to determine hierarchical relationships and support inactive statuses for …
> MAP-2476 Enhance cell certificate handling and validation

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/Cell.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/Location.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/service/LocationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/integration/CommonDataTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/CellCertificateResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationResidentialResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationResourceIntTest.kt
- src/test/resources/repository/insert-dummy-locations.sql
This pull request addresses updates to location management in the prison system, enforcing restrictions when locations are locked and improving test coverage for these scenarios. Minor library updates are also included.
- Library Update: Bumps the version of hmpps-digital-prison-reporting-lib from 8.3.3 to 8.3.4.
- Core Updates:
- Introduces a new validation to prevent updates to locked locations across various operations (Cell and Location).
- Adds a custom exception for locked locations: LockedLocationCannotBeUpdatedException.
- Testing Enhancements:
- Updates integration tests to validate behavior for locked locations.
- Introduces new test cases to verify restrictions on updating, converting, or renaming locked locations.
- SQL Adjustments: Modifies the test data cleanup in …
> MAP-2472 Add handling for locked locations, preventing updates and conversions

- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/dto/UpdateFromExternalSystemEvent.kt
Updated the method toUpdateFromExternalSystemDeactivateEvent to call .copy(updatedBy = who) after converting the object, likely to ensure the updatedBy field is explicitly set.
No other changes appear to be in this file; the modification is focused on improving how data is handled/transferred while using ObjectMapper.
> MAP-2504 Add support for propagating `updatedBy` field in deactivation event transformation.

- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/ResidentialLocation.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/service/CellCertificateService.kt
This Pull Request simplifies several method signatures and cleanses unnecessary parameters. It removes redundant arguments and streamlines calls to certain methods within the ResidentialLocation and CellCertificateService classes.
- Updated method definitions in ResidentialLocation to remove unnecessary parameters (certificationApprovalRequest or cellCertificate), ensuring cleaner function calls.
- Adjusted map operations to better align with the streamlined method signatures.
- Moved certain variable assignments and call chains for clearer and more readable flow, especially in CellCertificateService.
This PR primarily improves code readability and eliminates unused or redundant method arguments, aligning with principles of clean code.
> MAP-2510 Refactor location-to-entity mapping methods for approval requests and certifications

- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/dto/CreateEntireWingRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/ResidentialLocation.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/service/LocationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/integration/CommonDataTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/DraftLocationResourceTest.kt
This Pull Request introduces updates to handle and validate the hierarchical structure of prison wing levels. It ensures alignment of newly added locations with predefined structures, improves structure-related logic, and enhances testing for edge cases.
- DTO Updates:
- Added a field wingStructure to represent the structure of a wing in CreateEntireWingRequest.
- Included logic to apply wing structures during creation.
- JPA Entity Enhancements:
- Added the function getNextLevelTypeWithinStructure to validate the structure hierarchy.
- Updated getStructure to private for better encapsulation.
- Service Layer:
- Enhanced validation to ensure new levels adhere to the agreed wing structure.
- Refactored sub-location type determination to use getNextLevelTypeWithinStructure.
- Tests:
- Added …
> MAP-2596 Validate location type against wing structure and include wing structure in creation requests"

- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/config/ClientCachingOAuth2AuthorizedClientService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/config/OAuth2ClientConfiguration.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/integration/wiremock/HmppsAuthMockServer.kt
This pull request introduces client caching for OAuth2 authorized client management. It includes the addition of `ClientCachingOAuth2AuthorizedClientService` to optimise client handling. The configuration is updated to utilize the client credentials grant flow, and mock server responses are enhanced to include token expiry details. 
N/A
> MAP-2679 Introduce client caching for OAuth2 authorized client management

- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/dto/CellInitialisationRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/service/LocationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/DraftLocationResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationTransformResourceTest.kt
- Implemented the `isCapacityValid` method to ensure zero CNA and working capacity are validated consistently.
- Updated test cases to cover new validation logic and verify error handling.
- Improved error messages to better communicate the restrictions on zero capacity.
---
> MAP-2741 Enforce validation for zero CNA and working capacity in normal cells

- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/dto/CertificationApprovalRequestDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/CertificationApprovalRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/SignedOpCapCertificationApprovalRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/SignedOperationCapacity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/service/CertificationService.kt
- src/main/resources/db/migration/V1_67__reason_for_op_cap_change.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/CertificationResourceTest.kt
This pull request introduces support for including a reason related to signed operation capacity changes. Updates were made to DTOs, entities, services, migrations, and tests to implement and validate this feature.
> MAP-2773 Add reason for signed operation capacity change to DTOs, entities, services, migrations, and tests

- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/ResidentialLocation.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/service/LocationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/resource/LocationResidentialResourceTest.kt
This pull request adds a fallback mechanism to default to the next level type for sub-location descriptions within the `ResidentialSummary` component.
> MAP-2778 Add fallback to default next level type for sub-location descriptions in ResidentialSummary

- src/main/kotlin/uk/gov/justice/digital/hmpps/locationsinsideprison/jpa/CertificationApprovalRequest.kt
- src/main/resources/db/migration/V1_68__extend_specialist_cell_types_length.sql
- Increased the `specialist_cell_types` database column size to 4000 characters, enabling support for larger data.
- Updated visibility of properties in `CertificationApprovalRequest` to `open` for enhanced flexibility and extensibility.
No additional issues were linked with this pull request.
> MAP-2777 🐛 Extend `specialist_cell_types` length and update `CertificationApprovalRequest` visibility modifiers
